### ISSUE TITLE
False interlaced detection

### ISSUE THREAD

**Issue by Dobatymo** [Asd-g/AviSynth-FillBorders#2]
The check introduced here https://github.com/Asd-g/AviSynth-FillBorders/commit/f884afb650cc05c81032915ae1bee02e034fd1d5 doesn't always work. I have a clip which I read with
```
D2VSource(...)
QTGMC()
FillMargins()
```
and FillMargins fails with the `clip must be frame-based` error message. I checked with `propGetInt("_FieldBased")` and it yields 2 although clearly after using `QTGMC` the clip should be progressive. `IsFrameBased()` does yield True. It seems the `IsFrameBased()` function checks `image_type` not `_FieldType`.

Using `AviSynthPlus_3.7.2_20220317`

**Comment by Asd-g** [comment]
The issue is that `QTGMC` version you're using doesn't change `_FieldBased` to `0`. [Here](https://gitlab.com/uvz/AviSynthPlus-Plugins-Scripts/-/blob/master/scripts/QTGMC.avsi#L1015) a version that does change it ( https://gitlab.com/uvz/AviSynthPlus-Plugins-Scripts/-/commit/751e13abedc8e7472ac6975631cf18022cf46030 ). [Here](https://github.com/Dogway/Avisynth-Scripts/blob/master/MIX%20mods/QTGMC%2B.avsi#L1538) another `QTGMC` mod that does change it too.

**Comment by Dobatymo** [comment]
Thank you. Is https://github.com/realfinder/AVS-Stuff/raw/master/avs%202.6%20and%20up/QTGMC.avsi not the recommended version anymore?

**Comment by Asd-g** [comment]
This https://github.com/realfinder/AVS-Stuff/raw/master/avs%202.6%20and%20up/QTGMC.avsi version is the same as this one https://gitlab.com/uvz/AviSynthPlus-Plugins-Scripts/-/blob/master/scripts/QTGMC.avsi except that the latter one does change `_FieldBased`.

I did pr - https://github.com/realfinder/AVS-Stuff/pull/164
